// src/routes/Work.vue
<script setup lang="ts">
const projects = [
  {
    title: 'Healthcare SAAS',
    slogan: 'Responsive SaaS UI with demo-ready flows',
    description: 'Healthcare SaaS interface focused on a clean user experience, responsive workflows, and fast deployment.',
    url: 'https://healthcare-saas-789.netlify.app/login?user=demo',
    displayUrl: 'healthcare-saas-789.netlify.app',
    image: '/projects/healthcare-saas.png',
    tags: ['React.js', 'Node.js', 'Firebase', 'Tailwind CSS']
  },
  {
    title: 'AI Assistant',
    slogan: 'Agent experience, fast frontend, and Vercel delivery',
    description: 'Conversational AI assistant using Astro, React, Vite, Tailwind CSS, and Google Agent Development Kit.',
    url: 'https://agent-b7.vercel.app',
    displayUrl: 'agent-b7.vercel.app',
    image: '/projects/ai-assistance.png',
    tags: ['React.js', 'Python', 'Google ADK', 'Vercel']
  },
  {
    title: 'GearX AI',
    slogan: 'Product modules, admin workflows, and cloud delivery',
    description: 'User and admin modules for an AI product, built with modern React foundations and production deployment workflows.',
    url: 'https://gearx-ai-demo.netlify.app',
    displayUrl: 'gearx-ai-demo.netlify.app',
    image: '/projects/gearx.png',
    tags: ['React.js', 'Tailwind CSS', 'Node.js']
  },
  {
    title: 'My Dream Paints',
    slogan: 'Brand website with production deployment',
    description: 'Business website built with Next.js and Tailwind CSS, optimized for a polished responsive brand presence.',
    url: 'https://mydreampaints.com/',
    displayUrl: 'mydreampaints.com',
    image: '/projects/mydreampaints.png',
    tags: ['Next.js', 'Tailwind CSS']
  },
  {
    title: 'MKS Foods',
    slogan: 'Performance-focused business site',
    description: 'Food business website built and optimized with React.js, Next.js, Tailwind CSS, and Netlify CI/CD.',
    url: 'https://mksfoods.in/',
    displayUrl: 'mksfoods.com',
    image: '/projects/mksfoods.png',
    tags: ['React.js', 'Next.js', 'Tailwind CSS', 'Netlify']
  }
];

</script>

<template>
  <div class="flex flex-col gap-12 w-full mt-6 relative z-10">
    <!-- Header Hero -->
    <section class="flex flex-col gap-4 text-center items-center">
      <h1 class="text-3xl md:text-4xl font-extrabold font-display leading-tight tracking-tight bg-gradient-to-b from-text-primary via-text-primary to-text-secondary bg-clip-text text-transparent">
        Building premium web products across frontend, backend, AI, and delivery.
      </h1>
      <p class="text-sm md:text-base text-text-secondary leading-relaxed px-2">
        A focused overview of my production experience and shipped projects, from scalable React and Next.js interfaces to APIs, microservices, CI/CD, and AI-assisted development.
      </p>

    </section>

    <!-- Section Divider -->
    <hr class="border-border-weak/40 w-1/5 mx-auto" />

    <!-- Selected Builds Grid -->
    <section class="flex flex-col gap-6 mb-8">
      <div class="flex flex-col gap-1.5 text-center items-center">
        <h2 class="text-xs font-bold text-text-muted uppercase tracking-widest font-display">Selected Builds</h2>
        <p class="text-xs text-text-secondary max-w-md">
          Production and portfolio projects that show the range of my frontend, full-stack, cloud, and AI-focused work.
        </p>
      </div>

      <div class="grid grid-cols-1 gap-24 mt-4">
        <div 
          v-for="project in projects" 
          :key="project.title"
          class="bg-bg-card border border-border-weak hover:border-brand-strong/40 hover:-translate-y-1.5 hover:shadow-lg rounded-2xl overflow-hidden flex flex-col transition-all duration-300 group"
        >
          <!-- Image -->
          <div class="aspect-video w-full overflow-hidden bg-neutral-weak relative border-b border-border-weak">
            <img 
              :src="project.image" 
              :alt="project.title" 
              class="w-full h-full object-cover group-hover:scale-[1.03] transition-transform duration-500"
            />
            <div class="absolute inset-0 bg-neutral-900/10 group-hover:bg-neutral-900/0 transition-colors duration-300"></div>
          </div>

          <!-- Card Body -->
          <div class="p-5 flex flex-col gap-4 flex-1">
            <div class="flex flex-col gap-2">
              <div class="flex flex-col gap-0.5">
                <h3 class="text-lg font-bold font-display text-text-primary group-hover:text-brand-text transition-colors duration-200">
                  {{ project.title }}
                </h3>
                <span class="text-[10px] sm:text-[11px] text-brand-text font-bold uppercase tracking-wider">{{ project.slogan }}</span>
              </div>
              <p class="text-xs text-text-secondary leading-relaxed min-h-[50px]">
                {{ project.description }}
              </p>
            </div>

            <!-- Tech stack chips -->
            <div class="flex flex-wrap gap-1.5">
              <span 
                v-for="tag in project.tags" 
                :key="tag"
                class="inline-flex items-center gap-1 px-2.5 py-0.5 bg-neutral-weak border border-neutral-strong/10 text-[9px] uppercase font-bold tracking-wider text-text-secondary rounded-md"
              >
                <span class="w-1.5 h-1.5 rounded-full bg-text-muted/60"></span>
                {{ tag }}
              </span>
            </div>

            <!-- Card Footer -->
            <div class="flex items-center justify-between gap-4 mt-auto pt-3 border-t border-border-weak/40 text-xs">
              <span class="text-text-muted font-mono tracking-tight text-[11px]">{{ project.displayUrl }}</span>
              <a 
                v-if="project.url !== '#'"
                :href="project.url" 
                target="_blank" 
                rel="noopener noreferrer" 
                class="inline-flex items-center gap-1 text-brand-text hover:text-brand font-semibold group/link"
              >
                View project
                <svg class="w-3.5 h-3.5 group-hover/link:translate-x-0.5 group-hover/link:-translate-y-0.5 transition-transform duration-200" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 19.5l15-15m0 0H8.25m11.25 0v11.25" />
                </svg>
              </a>
              <span v-else class="text-[11px] text-text-muted font-semibold italic uppercase tracking-wider bg-neutral-weak border border-neutral-strong/10 px-2 py-0.5 rounded">Internal Build</span>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

// src/app/work/page.tsx
import { Badge, Column, Heading, Media, Meta, Row, Schema, SmartLink, Tag, Text } from "@once-ui-system/core";
import { baseURL, about, person, work } from "@/resources";

type WorkProject = {
  title: string;
  description: string;
  href: string;
  image: string;
  imageAlt: string;
  stack: string[];
  impact: string;
};

const projects: WorkProject[] = [
  {
    title: "Healthcare SAAS",
    description:
      "Healthcare SaaS interface focused on a clean user experience, responsive workflows, and fast deployment.",
    href: "https://healthcare-saas-789.netlify.app/login?user=demo",
    image: "/projects/healthcare-saas.png",
    imageAlt: "Healthcare SaaS project preview",
    stack: ["React.js", "Vite", "Tailwind CSS", "GitHub", "Netlify"],
    impact: "Responsive SaaS UI with demo-ready flows",
  },
  {
    title: "AI Assistant",
    description:
      "Conversational AI assistant using Astro, React, Vite, Tailwind CSS, and Google Agent Development Kit.",
    href: "https://bmn789.vercel.app",
    image: "/projects/ai-assistance.png",
    imageAlt: "AI Assistant project preview",
    stack: ["Astro.js", "React.js", "Vite", "Tailwind CSS", "Google ADK", "Vercel"],
    impact: "Agent experience, fast frontend, and Vercel delivery",
  },
  {
    title: "GearX AI",
    description:
      "User and admin modules for an AI product, built with modern React foundations and production deployment workflows.",
    href: "https://gearx.ai",
    image: "/projects/gearx.png",
    imageAlt: "GearX AI project preview",
    stack: ["React.js", "Next.js", "Tailwind CSS", "MUI", "GitLab", "AWS"],
    impact: "Product modules, admin workflows, and cloud delivery",
  },
  {
    title: "My Dream Paints",
    description:
      "Business website built with Next.js and Tailwind CSS, optimized for a polished responsive brand presence.",
    href: "https://www.mydreampaints.com",
    image: "/projects/mydreampaints.png",
    imageAlt: "My Dream Paints project preview",
    stack: ["Next.js", "JavaScript", "Tailwind CSS", "GitHub", "Vercel"],
    impact: "Brand website with production deployment",
  },
  {
    title: "MKS Foods",
    description:
      "Food business website built and optimized with React.js, Next.js, Tailwind CSS, and Netlify CI/CD.",
    href: "https://mksfoods.in",
    image: "/projects/mksfoods.png",
    imageAlt: "MKS Foods project preview",
    stack: ["React.js", "Next.js", "Tailwind CSS", "GitHub", "Netlify"],
    impact: "Performance-focused business site",
  },
];

export async function generateMetadata() {
  return Meta.generate({
    title: work.title,
    description: work.description,
    baseURL: baseURL,
    image: `/api/og/generate?title=${encodeURIComponent(work.title)}`,
    path: work.path,
  });
}

export default function Work() {
  return (
    <Column maxWidth="m" paddingTop="24" gap="xl">
      <Schema
        as="webPage"
        baseURL={baseURL}
        path={work.path}
        title={work.title}
        description={work.description}
        image={`/api/og/generate?title=${encodeURIComponent(work.title)}`}
        author={{
          name: person.name,
          url: `${baseURL}${about.path}`,
          image: `${baseURL}${person.avatar}`,
        }}
      />
      <Column
        className="work-hero-faint-gradient"
        fillWidth
        gap="24"
        padding="32"
        radius="xl"
        border="neutral-alpha-weak"
      >
        <Badge
          background="brand-alpha-weak"
          paddingX="12"
          paddingY="4"
          onBackground="brand-strong"
          textVariant="label-default-s"
          arrow={false}
        >
          Experience & Projects
        </Badge>
        <Column gap="12" maxWidth="s">
          <Heading as="h1" variant="display-strong-l" wrap="balance">
            Building premium web products across frontend, backend, AI, and delivery.
          </Heading>
          <Text variant="body-default-l" onBackground="neutral-weak">
            A focused overview of my production experience and shipped projects, from scalable
            React and Next.js interfaces to APIs, microservices, CI/CD, and AI-assisted
            development.
          </Text>
        </Column>
        <Row fillWidth gap="12" wrap>
          {["4+ years experience", "5 featured projects", "React / Next.js / Node.js", "AI-Augmented Development"].map(
            (item) => (
              <Tag key={item} size="l" variant="brand">
                {item}
              </Tag>
            ),
          )}
        </Row>
      </Column>

      <Column fillWidth gap="24" marginBottom="40">
        <Column gap="8">
          <Text variant="label-default-s" onBackground="brand-weak">
            Selected Builds
          </Text>
          <Heading as="h2" variant="display-strong-s">
            Projects
          </Heading>
          <Text variant="body-default-m" onBackground="neutral-weak">
            Production and portfolio projects that show the range of my frontend, full-stack,
            cloud, and AI-focused work.
          </Text>
        </Column>

        <Column fillWidth gap="32">
          {projects.map((project, index) => (
            <Column
              key={project.href}
              className="work-project-card"
              fillWidth
              gap="0"
              padding="0"
              radius="l"
              border="neutral-alpha-weak"
              background="page"
              overflow="hidden"
            >
              <SmartLink
                href={project.href}
                className="work-project-card-media-link"
                aria-label={`Open ${project.title}`}
                style={{ display: "block", width: "100%", margin: 0, textDecoration: "none" }}
              >
                <Media
                  priority={index < 2}
                  src={project.image}
                  alt={project.imageAlt}
                  aspectRatio="16 / 9"
                  fillWidth
                  border="neutral-alpha-weak"
                  cursor="interactive"
                  objectFit="cover"
                  sizes="(max-width: 768px) 100vw, min(880px, 92vw)"
                />
              </SmartLink>

              <Column fillWidth padding="24" gap="16">
                <Row fillWidth horizontal="between" vertical="start" gap="16" wrap s={{ direction: "column" }}>
                  <Column gap="8" flex={1} minWidth={0}>
                    <Row gap="12" vertical="center" wrap>
                      <Badge
                        background="brand-alpha-weak"
                        paddingX="12"
                        paddingY="4"
                        onBackground="brand-strong"
                        textVariant="label-default-s"
                        arrow={false}
                      >
                        {String(index + 1).padStart(2, "0")}
                      </Badge>
                      <Heading as="h3" variant="heading-strong-xl">
                        {project.title}
                      </Heading>
                    </Row>
                    <Text variant="body-default-m" onBackground="neutral-weak">
                      {project.description}
                    </Text>
                  </Column>
                  <SmartLink
                    href={project.href}
                    suffixIcon="arrowUpRightFromSquare"
                    className="home-project-action brand-on-background-weak"
                  >
                    <Text variant="body-default-s" onBackground="brand-weak">
                      View project
                    </Text>
                  </SmartLink>
                </Row>

                <Text variant="body-default-s" onBackground="neutral-weak">
                  {project.impact}
                </Text>

                <Row wrap gap="8">
                  {project.stack.map((item) => (
                    <Tag key={`${project.title}-${item}`} size="m" variant="accent">
                      {item}
                    </Tag>
                  ))}
                </Row>
              </Column>
            </Column>
          ))}
        </Column>
      </Column>
    </Column>
  );
}
